language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

addons:
  apt:
    packages:
      - git
      - mercurial
      - cmake
      - libpng-dev
      - libjpeg-dev
      - libtiff-dev
      - libglu1-mesa-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-serialization-dev
      - libopencv-dev
      - libcgal-dev
      - libatlas-base-dev
      - freeglut3-dev
      - libglew-dev
      - libglfw3-dev

before_install:
  - echo $LANG
  - export OMP_NUM_THREADS=4

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release

script:
  - make -j4

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master

notifications:
  email: true
